### ISSUE TITLE
printing to Zebra printer with required pocket label

### ISSUE THREAD

**Issue by HSteeleLTS** [ExLibrisGroup/spineomatic-cloudapp#27] opened 2021-06-11 10:29 UTC
Our issue is our Zebra printer through its configuration settings file embedded in the printer requires there to be a pocket label in the label print job that is sent to the printer. Both for workflow (it helps staff confirm they've scanned the right book) and because the label won't print without it, we need to be able to send the pocket label in data that is sent to the printer.

It looks given current functionality in the SpineOMatic cloud app this feature isn't supported, given this documentation. If this is the right place I wanted to forward this as an improvement for development https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help , but in the meantime I wondered if anyone had a hack/workaround for this? I've included snapshots of our settings and an image I was able to "hack" print with the attached settings.

![-hacked-spine-pocket label](https://user-images.githubusercontent.com/44376066/121672894-52df7b80-ca7e-11eb-8a3e-e9d8b9ee164e.jpg)
<img width="960" alt="layout" src="https://user-images.githubusercontent.com/44376066/121672911-583cc600-ca7e-11eb-9293-e6e9e1de7bc7.png">
<img width="960" alt="template" src="https://user-images.githubusercontent.com/44376066/121672925-5bd04d00-ca7e-11eb-8511-dc6a63513f90.png">

**Comment by jweisman** [comment] 2021-06-13 06:36
Hi @HSteeleLTS - this sounds like it's a duplicate of #23 - do you agree?

**Comment by HSteeleLTS** [comment] 2021-06-14 12:43
Yes indeed.  I also posted to the bottom of that thread.  Is this possible ?

Sent from my iPhone

On Jun 13, 2021, at 2:37 AM, Josh Weisman ***@***.***> wrote:

﻿

Hi @HSteeleLTS<https://github.com/HSteeleLTS> - this sounds like it's a duplicate of #23<https://github.com/ExLibrisGroup/spineomatic-cloudapp/issues/23> - do you agree?

**Comment by jweisman** [comment] 2021-06-15 02:55
Thanks - it's something we're exploring how to do. You can subscribe to #23 by clicking the subscribe button in that issue and get notifications. We'll update there when we have news.

<img width="340" alt="Screen Shot 2021-06-15 at 5 54 31 " src="https://user-images.githubusercontent.com/80420/121985883-43be3d80-cd9e-11eb-9187-55521f84ada3.png">

**Closed by jweisman** 2021-06-15 02:55 UTC
Labels: duplicate
