### ISSUE TITLE
Defining layout of barcode; printing barcode values does not always work

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/spineomatic-cloudapp#58] opened 2022-01-19 13:00 UTC
Hi,

I'm trying to duplicate our Aleph labels in Spineomatic. I'm close but still no cigar :) I'm having problems with the barcode and can't figure out what units are used to set the height and width of the labels. I have also checked the "Show barcode value" checkmark but it doesn't get printed on the label.  I have tried various numbers in the size configuration as well as using the default values but to no avail. I'm using the Code 39 barcode format.

Can you point me in the right direction?  Attached are two examples of current (Aleph) labels and what Spineomatic prints out in Alma.

Regards, 

Helgi Steindal
[lab19-01-2022-112652.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/7897241/lab19-01-2022-112652.pdf)

**Comment by mgobat** [comment] 2022-01-19 21:18
@kremke, could you provide complete details of your template and layout settings?

**Comment by mgobat** [comment] 2022-01-21 16:50
@kremke, just to make sure I'm understanding correctly, you created the label template in Microsoft Word, then did a copy from Word, and pasted into the "Label Contents" section while editing a Template in the SpineOMatic Cloud App.  Is that correct? If that is correct, while an absolutely brilliant way of creating the Label Contents, copying from Word to the SpineOMatic Cloud App exposes this problem.  

Here's my test case:

1. I first created a Template using the "Table" tool while editing a Template in SpineOMatic. I added only the barcode to one of the cells. I then printed a label using this template. Note that in the screenshot below, the top part is just that label, and the barcode value is printed.
2. I then edited the same template, pasting your label template from Word below my original manually created table. I then printed a label using the template. Note that in the lower portion of the screenshot, the first barcode printed without the barcode value this time.

It seems pasting from Word exposes this bug. I will look into a fix for this. 

![barcodesMissing](https://user-images.githubusercontent.com/45852490/150566570-1c8438d2-b4cb-4037-b298-cc000f896864.png)

**Comment by kremke** [comment] 2022-01-21 17:52
Hi,

Yes, this is how I did it.  I had been trying to get the table right in the Cloud app editor but every time I changed one cell's dimensions or added fields to be printed, others would change and I had no luck in making the label look like I wanted so I thought I might try to do it in Word.  Since everything else seemed to work, it never occurred to me that the barcode rendering was misbehaving due to the table being designed outside the inbuilt editor.  But with hindsight it stands to reason that Word would add some cruft to the table.

It also looks like there is an extra column in the table that I hadn't (knowingly) put there, but it might actually be a good way to create a margin.  The labels I'm trying to recreate here are the largest ones the libraries are using, on other labels the barcode takes up almost all the space in the top left corner so millimetre precision is necessary for the labels to print correctly and I just couldn't get the inbuilt editor to work for me. Attempting to do it in Word was worth a try, but if there are any open source or free table editors I would love to try them out.  

Regards,

Helgi

**Comment by mgobat** [comment] 2022-01-21 21:14
While looking for a fix, I discovered the issue is not specially related to copy/paste from Word. Its a defect that could affect the printing of the barcode value regardless of how it is added to the template.

**Comment by mgobat** [comment] 2022-01-24 18:26
New field, "Barcode font size", added to the "Barcode" options in "Templates". This field will be used as the barcode font size if one is not found in the template. This is done to keep the Cloud App backwards compatible with existing templates. However, this new field is the preferred method of defining the barcode font size, and if set, will override a value in the template.

Fixed in release v1.2.0.

**Closed by mgobat** 2022-01-24 18:26 UTC
Labels: bug
